// Code generated by hwgen. DO NOT EDIT.
package basic

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// Ensure imports are used.
var (
	_ = bytes.NewBuffer
	_ = context.Background
	_ = json.Marshal
	_ = fmt.Sprintf
	_ io.Reader
)

// Client is a typed HTTP client for calling the generated endpoints.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
}

// NewClient creates a new Client with the given base URL.
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL:    baseURL,
		HTTPClient: http.DefaultClient,
	}
}

// CreateUser calls POST /users.
func (c *Client) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	var body bytes.Buffer
	if err := req.Serialize(&body); err != nil {
		return nil, fmt.Errorf("serializing request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+"/users", &body)
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpRes, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("executing request: %w", err)
	}
	defer httpRes.Body.Close()

	if httpRes.StatusCode >= 400 {
		var clientErr ClientError
		if err := json.NewDecoder(httpRes.Body).Decode(&clientErr); err != nil {
			return nil, fmt.Errorf("server returned status %d", httpRes.StatusCode)
		}
		clientErr.StatusCode = httpRes.StatusCode
		return nil, &clientErr
	}

	res := &CreateUserResponse{}
	if err := res.Deserialize(httpRes.Body); err != nil {
		return nil, fmt.Errorf("deserializing response: %w", err)
	}
	return res, nil
}

// GetTime calls GET /time.
func (c *Client) GetTime(ctx context.Context, req *GetTimeRequest) (*GetTimeResponse, error) {
	var body bytes.Buffer
	if err := req.Serialize(&body); err != nil {
		return nil, fmt.Errorf("serializing request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "GET", c.BaseURL+"/time", &body)
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpRes, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("executing request: %w", err)
	}
	defer httpRes.Body.Close()

	if httpRes.StatusCode >= 400 {
		var clientErr ClientError
		if err := json.NewDecoder(httpRes.Body).Decode(&clientErr); err != nil {
			return nil, fmt.Errorf("server returned status %d", httpRes.StatusCode)
		}
		clientErr.StatusCode = httpRes.StatusCode
		return nil, &clientErr
	}

	res := &GetTimeResponse{}
	if err := res.Deserialize(httpRes.Body); err != nil {
		return nil, fmt.Errorf("deserializing response: %w", err)
	}
	return res, nil
}

// HealthCheck calls POST /health.
func (c *Client) HealthCheck(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	var body bytes.Buffer
	if err := req.Serialize(&body); err != nil {
		return nil, fmt.Errorf("serializing request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+"/health", &body)
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpRes, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("executing request: %w", err)
	}
	defer httpRes.Body.Close()

	if httpRes.StatusCode >= 400 {
		var clientErr ClientError
		if err := json.NewDecoder(httpRes.Body).Decode(&clientErr); err != nil {
			return nil, fmt.Errorf("server returned status %d", httpRes.StatusCode)
		}
		clientErr.StatusCode = httpRes.StatusCode
		return nil, &clientErr
	}

	res := &HealthCheckResponse{}
	if err := res.Deserialize(httpRes.Body); err != nil {
		return nil, fmt.Errorf("deserializing response: %w", err)
	}
	return res, nil
}

// ClientError represents an error response from the server.
type ClientError struct {
	StatusCode int    `json:"status_code"`
	Err        string `json:"error"`
}

func (e *ClientError) Error() string {
	return fmt.Sprintf("[%d] %s", e.StatusCode, e.Err)
}
