// Code generated by hwgen. DO NOT EDIT.
package basic

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	heartwood "github.com/bbsify-landed/heartwood/pkg/heartwood"
)

// Ensure imports are used.
var (
	_ = context.Background
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = io.EOF
	_ = strings.Join
	_ heartwood.App
)

// --- CreateUser ---

// CreateUserRequest is the request type for POST /users.
type CreateUserRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   int    `json:"age"`
}

func (r *CreateUserRequest) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *CreateUserRequest) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}

func (r *CreateUserRequest) Validate() error {
	var errs []string
	if r.Name == "" {
		errs = append(errs, "name is required")
	}
	if len(r.Name) < 1 {
		errs = append(errs, "name must be at least 1 characters")
	}
	if len(r.Name) > 100 {
		errs = append(errs, "name must be at most 100 characters")
	}
	if r.Email == "" {
		errs = append(errs, "email is required")
	}
	if float64(r.Age) < 0 {
		errs = append(errs, "age must be at least 0")
	}
	if float64(r.Age) > 150 {
		errs = append(errs, "age must be at most 150")
	}
	if len(errs) > 0 {
		return fmt.Errorf("validation failed: %s", strings.Join(errs, "; "))
	}
	return nil
}

// CreateUserResponse is the response type for POST /users.
type CreateUserResponse struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   int    `json:"age"`
}

func (r *CreateUserResponse) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *CreateUserResponse) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}

func (r *CreateUserResponse) Validate() error { return nil }

// CreateUserHandler is the handler function type for POST /users.
type CreateUserHandler func(ctx context.Context, req *CreateUserRequest) (error, *CreateUserResponse)

// RegisterCreateUser registers the CreateUser handler on the given app.
func RegisterCreateUser(app *heartwood.App, h CreateUserHandler) {
	heartwood.Use(app, "POST", "/users", func(ctx context.Context, req *CreateUserRequest) (error, *CreateUserResponse) {
		return h(ctx, req)
	})
}

// --- HealthCheck ---

// HealthCheckRequest is the request type for POST /health.
type HealthCheckRequest struct {
	AreYouHealthy string `json:"are_you_healthy"`
}

func (r *HealthCheckRequest) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *HealthCheckRequest) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}

func (r *HealthCheckRequest) Validate() error {
	var errs []string
	if r.AreYouHealthy == "" {
		errs = append(errs, "are_you_healthy is required")
	}
	if len(errs) > 0 {
		return fmt.Errorf("validation failed: %s", strings.Join(errs, "; "))
	}
	return nil
}

// HealthCheckResponse is the response type for POST /health.
type HealthCheckResponse struct {
	Healthy string `json:"healthy"`
}

func (r *HealthCheckResponse) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *HealthCheckResponse) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}

func (r *HealthCheckResponse) Validate() error { return nil }

// HealthCheckHandler is the handler function type for POST /health.
type HealthCheckHandler func(ctx context.Context, req *HealthCheckRequest) (error, *HealthCheckResponse)

// RegisterHealthCheck registers the HealthCheck handler on the given app.
func RegisterHealthCheck(app *heartwood.App, h HealthCheckHandler) {
	heartwood.Use(app, "POST", "/health", func(ctx context.Context, req *HealthCheckRequest) (error, *HealthCheckResponse) {
		return h(ctx, req)
	})
}
