package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"github.com/bbsify-landed/heartwood/pkg/schema"
)

// generate writes the generated Go files into dir for the given definitions.
func generate(dir string, pkgName string, defs map[string]*schema.Definition) error {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	data := templateData{
		Package:     pkgName,
		Definitions: make([]defData, 0, len(defs)),
	}

	for _, name := range names {
		def := defs[name]
		dd := defData{
			Name:     name,
			Method:   def.Method,
			Path:     def.Path,
			Request:  convertFields(def.ReqFields),
			Response: convertFields(def.ResFields),
		}
		data.Definitions = append(data.Definitions, dd)
	}

	if err := writeTemplate(filepath.Join(absDir, "hw_gen.go"), mainTmpl, data); err != nil {
		return fmt.Errorf("generating hw_gen.go: %w", err)
	}

	if err := writeTemplate(filepath.Join(absDir, "hw_client_gen.go"), clientTmpl, data); err != nil {
		return fmt.Errorf("generating hw_client_gen.go: %w", err)
	}

	return nil
}

type templateData struct {
	Package     string
	Definitions []defData
}

type defData struct {
	Name     string
	Method   string
	Path     string
	Request  []fieldData
	Response []fieldData
}

type fieldData struct {
	Name       string
	JSONName   string
	GoType     string
	IsRequired bool
	MinLen     *int
	MaxLen     *int
	Min        *float64
	Max        *float64
	IsString   bool
	IsNumeric  bool
	IsSlice    bool
}

func convertFields(fields []schema.Field) []fieldData {
	out := make([]fieldData, 0, len(fields))
	for _, f := range fields {
		fd := fieldData{
			Name:       toPascalCase(f.Name),
			JSONName:   f.Name,
			GoType:     goType(f),
			IsRequired: f.IsRequired,
			MinLen:     f.MinLen,
			MaxLen:     f.MaxLen,
			Min:        f.Min,
			Max:        f.Max,
			IsString:   f.Type == schema.StringType,
			IsNumeric:  f.Type == schema.IntType || f.Type == schema.Int64Type || f.Type == schema.Float64Type,
			IsSlice:    f.Type == schema.SliceType || f.Type == schema.SliceRefType,
		}
		out = append(out, fd)
	}
	return out
}

func goType(f schema.Field) string {
	switch f.Type {
	case schema.StringType:
		return "string"
	case schema.IntType:
		return "int"
	case schema.Int64Type:
		return "int64"
	case schema.Float64Type:
		return "float64"
	case schema.BoolType:
		return "bool"
	case schema.RefType:
		return "*" + f.RefName + "Message"
	case schema.SliceType:
		return "[]" + scalarGoType(f.ElemType)
	case schema.SliceRefType:
		return "[]*" + f.RefName + "Message"
	default:
		return "any"
	}
}

func scalarGoType(ft schema.FieldType) string {
	switch ft {
	case schema.StringType:
		return "string"
	case schema.IntType:
		return "int"
	case schema.Int64Type:
		return "int64"
	case schema.Float64Type:
		return "float64"
	case schema.BoolType:
		return "bool"
	default:
		return "any"
	}
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	var out strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		out.WriteString(string(runes))
	}
	return out.String()
}

func writeTemplate(path string, tmplStr string, data templateData) error {
	funcMap := template.FuncMap{
		"hasValidation": func(fields []fieldData) bool {
			for _, f := range fields {
				if f.IsRequired || f.MinLen != nil || f.MaxLen != nil || f.Min != nil || f.Max != nil {
					return true
				}
			}
			return false
		},
		"derefInt": func(p *int) int {
			if p == nil {
				return 0
			}
			return *p
		},
		"derefFloat": func(p *float64) float64 {
			if p == nil {
				return 0
			}
			return *p
		},
	}

	tmpl, err := template.New("gen").Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		_ = os.WriteFile(path, buf.Bytes(), 0o644)
		return fmt.Errorf("formatting generated code (written unformatted to %s): %w", path, err)
	}

	return os.WriteFile(path, formatted, 0o644)
}

var mainTmpl = `// Code generated by hwgen. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	heartwood "github.com/bbsify-landed/heartwood"
)

// Ensure imports are used.
var (
	_ = context.Background
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = io.EOF
	_ = strings.Join
	_ heartwood.App
)
{{ range .Definitions }}
// --- {{ .Name }} ---

// {{ .Name }}Request is the request type for {{ .Method }} {{ .Path }}.
type {{ .Name }}Request struct {
{{- range .Request }}
	{{ .Name }} {{ .GoType }} ` + "`" + `json:"{{ .JSONName }}"` + "`" + `
{{- end }}
}

func (r *{{ .Name }}Request) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *{{ .Name }}Request) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}
{{ if hasValidation .Request }}
func (r *{{ .Name }}Request) Validate() error {
	var errs []string
{{- range .Request }}
{{- if .IsRequired }}
{{- if .IsString }}
	if r.{{ .Name }} == "" {
		errs = append(errs, "{{ .JSONName }} is required")
	}
{{- else if .IsSlice }}
	if len(r.{{ .Name }}) == 0 {
		errs = append(errs, "{{ .JSONName }} is required")
	}
{{- end }}
{{- end }}
{{- if .MinLen }}
{{- if .IsString }}
	if len(r.{{ .Name }}) < {{ derefInt .MinLen }} {
		errs = append(errs, "{{ .JSONName }} must be at least {{ derefInt .MinLen }} characters")
	}
{{- else if .IsSlice }}
	if len(r.{{ .Name }}) < {{ derefInt .MinLen }} {
		errs = append(errs, "{{ .JSONName }} must have at least {{ derefInt .MinLen }} items")
	}
{{- end }}
{{- end }}
{{- if .MaxLen }}
{{- if .IsString }}
	if len(r.{{ .Name }}) > {{ derefInt .MaxLen }} {
		errs = append(errs, "{{ .JSONName }} must be at most {{ derefInt .MaxLen }} characters")
	}
{{- else if .IsSlice }}
	if len(r.{{ .Name }}) > {{ derefInt .MaxLen }} {
		errs = append(errs, "{{ .JSONName }} must have at most {{ derefInt .MaxLen }} items")
	}
{{- end }}
{{- end }}
{{- if .Min }}
{{- if .IsNumeric }}
	if float64(r.{{ .Name }}) < {{ derefFloat .Min }} {
		errs = append(errs, "{{ .JSONName }} must be at least {{ derefFloat .Min }}")
	}
{{- end }}
{{- end }}
{{- if .Max }}
{{- if .IsNumeric }}
	if float64(r.{{ .Name }}) > {{ derefFloat .Max }} {
		errs = append(errs, "{{ .JSONName }} must be at most {{ derefFloat .Max }}")
	}
{{- end }}
{{- end }}
{{- end }}
	if len(errs) > 0 {
		return fmt.Errorf("validation failed: %s", strings.Join(errs, "; "))
	}
	return nil
}
{{ else }}
func (r *{{ .Name }}Request) Validate() error { return nil }
{{ end }}
// {{ .Name }}Response is the response type for {{ .Method }} {{ .Path }}.
type {{ .Name }}Response struct {
{{- range .Response }}
	{{ .Name }} {{ .GoType }} ` + "`" + `json:"{{ .JSONName }}"` + "`" + `
{{- end }}
}

func (r *{{ .Name }}Response) Serialize(w io.Writer) error {
	return json.NewEncoder(w).Encode(r)
}

func (r *{{ .Name }}Response) Deserialize(rd io.Reader) error {
	return json.NewDecoder(rd).Decode(r)
}

func (r *{{ .Name }}Response) Validate() error { return nil }

// {{ .Name }}Handler is the handler function type for {{ .Method }} {{ .Path }}.
type {{ .Name }}Handler func(ctx context.Context, req *{{ .Name }}Request) (*{{ .Name }}Response, error)

// Register{{ .Name }} registers the {{ .Name }} handler on the given app.
func Register{{ .Name }}(app *heartwood.App, h {{ .Name }}Handler) {
	heartwood.Use(app, "{{ .Method }}", "{{ .Path }}", func(ctx context.Context, req *{{ .Name }}Request) (*{{ .Name }}Response, error) {
		return h(ctx, req)
	})
}
{{ end }}
`

var clientTmpl = `// Code generated by hwgen. DO NOT EDIT.
package {{ .Package }}

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// Ensure imports are used.
var (
	_ = bytes.NewBuffer
	_ = context.Background
	_ = json.Marshal
	_ = fmt.Sprintf
	_ io.Reader
)

// Client is a typed HTTP client for calling the generated endpoints.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
}

// NewClient creates a new Client with the given base URL.
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL:    baseURL,
		HTTPClient: http.DefaultClient,
	}
}
{{ range .Definitions }}
// {{ .Name }} calls {{ .Method }} {{ .Path }}.
func (c *Client) {{ .Name }}(ctx context.Context, req *{{ .Name }}Request) (*{{ .Name }}Response, error) {
	var body bytes.Buffer
	if err := req.Serialize(&body); err != nil {
		return nil, fmt.Errorf("serializing request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "{{ .Method }}", c.BaseURL+"{{ .Path }}", &body)
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpRes, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("executing request: %w", err)
	}
	defer httpRes.Body.Close()

	if httpRes.StatusCode >= 400 {
		var clientErr ClientError
		if err := json.NewDecoder(httpRes.Body).Decode(&clientErr); err != nil {
			return nil, fmt.Errorf("server returned status %d", httpRes.StatusCode)
		}
		clientErr.StatusCode = httpRes.StatusCode
		return nil, &clientErr
	}

	res := &{{ .Name }}Response{}
	if err := res.Deserialize(httpRes.Body); err != nil {
		return nil, fmt.Errorf("deserializing response: %w", err)
	}
	return res, nil
}
{{ end }}
// ClientError represents an error response from the server.
type ClientError struct {
	StatusCode int    ` + "`" + `json:"status_code"` + "`" + `
	Err        string ` + "`" + `json:"error"` + "`" + `
}

func (e *ClientError) Error() string {
	return fmt.Sprintf("[%d] %s", e.StatusCode, e.Err)
}
`
